---
- hosts: vagrant_libvirt
  become: True
  gather_facts: False
  connection: local
  vars:
    vyos_platform: vagrant-libvirt
    vyos_format: box
    vyos_vagrant_libvirt_box: "vyos_vagrant_libvirt_image.box"
    vyos_output_img: "{{ vyos_vagrant_libvirt_box }}"
    cloud_init: False
    enable_dhcp: True
    enable_ssh: True
    vagrant_provider: libvirt
    # Vagrant Default insecure key - see: https://github.com/hashicorp/vagrant/tree/main/keys
    default_ssh_key: "AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ=="
  roles:
    - install-packages
    - download-iso
    - mount-iso
    - get-version
    - create-disk
    - setup-root-partition
    - install-image
    - mount-root-fs
    - install-config
    - install-grub
    - install-persistence-conf
    - unmount-pre
    - unmount-all
    - vagrant-libvirt-box
    - release-vagrant-box
